-- Active: 1665848805213@@143.244.167.203@3306@BD2_Practica2

SHOW TABLEs;

SELECT COUNT(*) from `HABITACION`
UNION
SELECT distinct COUNT(*) from `LOG_ACTIVIDAD`
UNION
SELECT COUNT(*) from `LOG_HABITACION`
UNION
SELECT COUNT(*) from `PACIENTE`;


-- Borrar Modelo
drop TABLE `LOG_ACTIVIDAD`;
DROP TABLE `LOG_HABITACION`;
DROP TABLE `HABITACION`;
DROP TABLE `PACIENTE`;